version: 2

project_name: helm-upgrade-check-plugin

release:
  github:
    owner: bcurnow
    name: helm-upgrade-check-plugin
  draft: false
  prerelease: "false"

builds:
  - id: helm-upgrade-check-plugin
    main: ./cmd/helm-upgrade-check
    binary: helm-upgrade-check
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.Version={{.Version}}
    mod_timestamp: '{{ .CommitTimestamp }}'

archives:
  - format: binary

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch

env_files:
  github_token: ~/.config/goreleaser/helm-upgrade-check-plugin-github-token
